services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Solidwork\ContaoSolidCounterBundle\:
    resource: ../../*
    exclude:
      - ../../DependencyInjection/
      - ../../ContaoManager/
      - ../../Resources/
